apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hub-functions
    name: hub-functions
  name: hub-functions
  namespace: onify-citizen-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hub-functions
      task: hub-functions
  serviceName: hub-functions
  template:
    metadata:
      labels:
        app: hub-functions
        task: hub-functions
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
          image: eu.gcr.io/onify-images/citizen-functions:v2.50-rc1
          imagePullPolicy: Always
          name: hub-functions
          ports:
            - containerPort: 8282
              name: hub-functions
              protocol: TCP
      imagePullSecrets:
        - name: onify-regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hub-functions
  namespace: onify-citizen-test
spec:
  ports:
    - name: hub-functions
      port: 8282
      protocol: TCP
  selector:
    app: hub-functions
    task: hub-functions
  type: ClusterIP
