apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: onify-worker
    name: onify-worker
  name: onify-worker
  namespace: onify-citizen-test
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: onify-worker
      task: onify-worker
  serviceName: onify-worker
  template:
    metadata:
      labels:
        app: onify-worker
        task: onify-worker
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - worker
          env:
            - name: ENV_PREFIX
              value: ONIFY_
            - name: INTERPRET_CHAR_AS_DOT
              value: _
            - name: NODE_ENV
              value: development
            - name: ONIFY_adminUser_email
              value: admin@onify.local
            - name: ONIFY_adminUser_password
              value: Sup3rS3cretP@ssw#rd
            - name: ONIFY_adminUser_username
              value: admin
            - name: ONIFY_apiTokens_app_secret
              value: 1y0isq/dicJGsvKA/nTZledJZuplzdYF3cxD7sEIbwV6E1q5Ha
            - name: ONIFY_autoinstall
              value: "true"
            - name: ONIFY_client_code
              value: acme
            - name: ONIFY_client_instance
              value: test
            - name: ONIFY_client_secret
              value: 9m6GKvjLePxobMezGf2=lrpzQGcHMgP29XpnXaA3/z3CK
            - name: ONIFY_db_indexPrefix
              value: onify
            - name: ONIFY_initialLicense
              value: SOMELICENSE
            - name: ONIFY_logging_elasticFlushInterval
              value: "500"
            - name: ONIFY_logging_log
              value: stdout,elastic
            - name: ONIFY_resources_baseDir
              value: /usr/share/onify/resources
            - name: ONIFY_resources_tempDir
              value: /usr/share/onify/temp_resources
            - name: ONIFY_worker_cleanupInterval
              value: "300"
            - name: ONIFY_db_elasticsearch_host
              value: http://onify-elasticsearch:9200
          image: eu.gcr.io/onify-images/hub/api:2.41.0
          imagePullPolicy: Always
          name: onify-worker
          ports:
            - containerPort: 8181
              name: onify-worker
              protocol: TCP
      imagePullSecrets:
        - name: onify-regcred
